spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: auth-ms
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**

          - id: ticket-ms
            uri: http://localhost:8082
            predicates:
              - Path=/api/ticket/**

          - id: payment-ms
            uri: http://localhost:8083
            predicates:
              - Path=/api/payment/**

          - id: notification-ms
            uri: http://localhost:8084
            predicates:
              - Path=/api/notification/**

          - id: file-ms
            uri: http://localhost:8085
            predicates:
              - Path=/api/file/**

gateway:
  open-endpoints:
    - /api/auth/register
    - /api/auth/login

jwt:
  secret: "CHANGE_TO_32+_CHAR_RANDOM_SECRET"
  access-exp: 900000    # 15 minutes
  refresh-exp: 604800000 # 7 days
